# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6fc7f5df143671c047d7d7100e7d5d52f5ab2b3f794ce0b28ba1518296e4e5634b3b07ecaf9e60496312c6ab26c0b5100c6de8c8175155a9650268cc0815d79

test:
  secret_key_base: e20805c631abdd268deded067bc1a832ece5abdb7baf4091f8f68583802bb0372d2466bd371c9f149fa71e0bbf0583f34d3778ce02a6879e0f4d6adb8f803c5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
